#ifndef RESOURCEHOLDERS_RESOURCEIDENTIFIERS_H
#define RESOURCEHOLDERS_RESOURCEIDENTIFIERS_H

enum class TextureID {
    None,
};

enum class FontID {
    None,
};

#endif // RESOURCEHOLDERS_RESOURCEIDENTIFIERS_H
